t = int(input("Enter the number of travelers: "))
print("Where will we visits?")
p1 = input("Place 1: ")
p2 = input("Place 2: ")
p3 = input("Place 3: ")
dt1 = int(input("Enter the distance of the home to {} (km): ".format(p1)))
dt2 = int(input("Enter the distance of the {} to {} (km): ".format(p1, p2)))
dt3 = int(input("Enter the distance of the {} to {} (km): ".format(p2, p3)))
dt4 = int(input("Enter the distance of the {} to home (km): ".format(p3)))
g = int(input("Enter the gas price (bath per km): "))
d = int(input("Number of the day(s): "))
n = int(input("Number of the night(s): "))
htr = int(input("Enter the hotel price (bath per night): "))
fcp = int(input("Enter the food cost per person: "))

print("")
print("--- Your Trip Info ---")
print("Total distances =", str(float(dt1+dt2+dt3+dt4)), "km")
print("Total gas cost =", str(float((dt1+dt2+dt3+dt4) * g)), "bath")
print("Total hotel cost =", str(float(t * htr)), "bath")
print("Total shared cost =", str(float((t * htr) + ((dt1 + dt2 + dt3 + dt4) * g))), "bath")
print("Food cost per person =", float(fcp), "bath")
print("Total cost per person =", str(float(((t * htr) + ((dt1 + dt2 + dt3 + dt4) * g) + (fcp * t)) / t)), "bath")